### ISSUE TITLE
Background new tabs

### ISSUE THREAD

**Issue by JonnyThree** [Enchufadoo/fixedzoom#1]
Hello, first of all this is a really useful extension and i really appreciate your work for the made of it.
I found a bug that the custom zoom level is not applied when i right-click a link on any page and i want to open it in a new tab. 
I have Firefox 60.0.1 installed on a Windows 7 PC, and Firefox is setted to open links in new background tabs.
I really thanks you if you can fix this annoying bug.

**Comment by Enchufadoo** [comment]
Hi, thanks for reporting the bug. You are right, I'm sick today but Ill look into it as soon as I can.

**Comment by JonnyThree** [comment]
i thanks you for the fast answer

**Comment by Enchufadoo** [comment]
Fixed in the last version (1.3.1)

**Comment by JonnyThree** [comment]
yes, i can confirm. so many thanks...
