### ISSUE TITLE
Setting a custom zoom with ctrl +/- should automatically create a custom rule in the extension

### ISSUE THREAD

**Issue by PLyczkowski** [Enchufadoo/fixedzoom#10]
Alternatively, the extension should use custom zooms stored by firefox if that's possible?

**Comment by Enchufadoo** [comment]
Hi @PLyczkowski, it's a complicated issue, the problem is that I don't know if that's desirable. Imagine perhaps that someone wants to zoom an image in yahoo.com to see it closer. 
That would create a rule for the entire site, which may not be what most people want.

There's also the problem on how to do it, I think it's possible, but I'm more concern with whether it's something that the extension needs.

Maybe I could add a button to the popup icon that says, **save current zoom**? 
I'm all in for making the extension more simple.

**Comment by Enchufadoo** [comment]
Regarding grabbing the zoom stored by firefox, there is one case when it's impossible: when the stored zoom is 100%. Firefox doesn't say when the zoom is saved by the user and when it's set by the browser itself. So that I'm afraid I can't do it as far as I know.

**Comment by PLyczkowski** [comment]
>Imagine perhaps that someone wants to zoom an image in yahoo.com

Give an example url so we are on the same page (literally). As far as I can see your addon just does whole pages, not single images.
In the case of a internet gallery of some sort, I would think that if a user zooms in on a single image page (example https://www.deviantart.com/raichiyo33/art/SpiderGwen-764779624 ), then he/she wants all the single image pages on that site to be zoomed in.

>Maybe I could add a button to the popup icon that says, save current zoom?

I would prefer an option, off by default, called "Save site rule on manual zoom change" or something like that.

**Comment by Enchufadoo** [comment]
> As far as I can see your addon just does whole pages, not single images.

This image
https://www.reddit.com/r/FindTheSniper/comments/9efbmv/find_the_sniper/
, I usually just want the zoom to stay the same as before after I zoom in.

> I would prefer an option, off by default, called "Save site rule on manual zoom change" or something like that.

I can't intercept all the zoom changes made by the user, you said ctrl + / - which may be possible but firefox has many ways of changing the zoom. For example ctrl + wheel, pinching a touchscreen, if you mess around the settings you can use alt / shift + wheel or disable the wheel changes altogether. 

All this things are not accessible to the extension developer AFIK.

**Comment by Enchufadoo** [comment]
I played a couple of hours with this but I can't do it.

(technical explanation)
The browser behaves really weird on some sites for example if I change the zoom to 90% I may see this on tabs.onZoomChange https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onZoomChange
```
Tab: 1 zoomed 
Old zoom: 1 
New zoom: 0.9 
Tab: 1 zoomed 
Old zoom: 0.9 
New zoom: 1 
Tab: 1 zoomed 
Old zoom: 1 
New zoom: 0.9
```
Sometimes it just fails silently and doesn't execute the handler, I'm out of my depth with this.

**Comment by PLyczkowski** [comment]
I see. Thanks for trying though!

**Comment by Enchufadoo** [comment]
Figured out how to implement it but there's one catch: you have to wait for the page to finish loading for the zoom to be saved. I haven't tested it thoroughly but it should work.

To enable it go to advanced settings:

![imagen](https://user-images.githubusercontent.com/1263356/46190644-d0f99500-c2ca-11e8-8f94-143ea13e6204.png)

Version (1.9)

**Comment by PLyczkowski** [comment]
Nice! Thanks!
