### ISSUE TITLE
The zoom slider's bar isn't visible

### ISSUE THREAD

**Issue by ris58h** [Enchufadoo/fixedzoom#12]
![fixed-zoom-popup-problem](https://user-images.githubusercontent.com/511242/47455744-4fb6f480-d7db-11e8-9408-c11e399063f3.png)

Firefox version: 63.0

**Comment by Enchufadoo** [comment]
I can't seem to reproduce the error (win7/win 10/ ubuntu kde) I take you use linux?

Have you changed firefox CSS? I load some browser stylesheets (dumb idea in retrospective) so maybe that's the problem.

**Comment by ris58h** [comment]
Yep, it's Ubuntu 18.10 and I haven't changed Firefox's CSS (at least manually).

**Comment by Enchufadoo** [comment]
Maybe it's related to this
https://bugzilla.mozilla.org/show_bug.cgi?id=1501858

A guy posts a very similar image
https://bugzilla.mozilla.org/attachment.cgi?id=9019851

Can you please check if you can see the input on this page:
https://codepen.io/anon/pen/bmZjEZ

or entering this address on the browser:
`data:text/html,<input type="range" />`

**Comment by ris58h** [comment]
Slider from the example isn't visible, so yes - it's a Firefox issue.
