### ISSUE TITLE
Rules weirdness

### ISSUE THREAD

**Issue by hmijail** [Enchufadoo/fixedzoom#13]
I enabled the option for automatically creating rules, changed manually the zoom in a couple of sites (github.com among them), and it started alternating between the manual value and the default value about twice per second. 
It didn't happen from the very beginning; looks like opening a new tab to the site causes the behavior to start even in existing tabs in another window.
When I tried deleting the rules, the list of rules would be emptied, but the behavior continued and on reload the github rules was there again. I have had to disable the manual creation and delete the rules for things to stabilize.

Other than that, great work :)

**Comment by Enchufadoo** [comment]
Damn, that's terrible, I will see if I can reproduce the error. The method I use is kind of a hack so I guess I'll have to figure out a better way.
Thanks for reporting it.

**Comment by Enchufadoo** [comment]
Added some changes in last version to fix this (1.9.6). Hope it works.
