### ISSUE TITLE
Light icon for dark themes

### ISSUE THREAD

**Issue by edjroot** [Enchufadoo/fixedzoom#17]
The title is self-descriptive. The icon is invisible in dark themes. I'd say the optimal solution would be a toggle for light/dark, so all users would be able to see it.

Thanks a lot for developing this add-on! :)

**Comment by Enchufadoo** [comment]
Added on last version (2.0.0)

I just made the dark theme version totally white, hope it's enough.

![imagen](https://user-images.githubusercontent.com/1263356/48969832-44760500-efe3-11e8-8ae9-d630fced5d75.png)

It probably sucks if you have a persona with a light color and the dark theme enabled.

**Comment by edjroot** [comment]
It does work for me, thanks!

But I'd say the optimal solution would be a toggle for light/dark, so all users would be able to see it. Sorry for not describing the idea from the start.

**Comment by Enchufadoo** [comment]
Is there an extension that does that?

**Comment by edjroot** [comment]
Yes, I've come across quite a few that do. Off the top of my head there's SimpleExtManager:

![SimpleExtManager](https://user-images.githubusercontent.com/3580075/48974107-a0697980-f035-11e8-9e5f-ddfe8292cec8.png) (simple checkbox)

and LastPass:

![LastPass](https://user-images.githubusercontent.com/3580075/48974104-8760c880-f035-11e8-96ef-c689e80045a2.png) (multiple options).

**Comment by Enchufadoo** [comment]
Sorry, now I understand what you want, I thought it had something to do with dark/light global theme.

**Comment by edjroot** [comment]
Oh, no problems, sorry if I wasn't clear enough!

**Comment by Enchufadoo** [comment]
No no, my bad, I'll add it.

**Comment by Enchufadoo** [comment]
Added on last version (2.0.1) in advanced settings.

![imagen](https://user-images.githubusercontent.com/1263356/48979255-b8bdb080-f096-11e8-9307-327ea495d58c.png)

I tried to added the option to select any color but the base black icon shows for a second before changing which is kind of buggy, I leave the code for future reference

https://gist.github.com/Enchufadoo/ec1497cbc2265ae1a24e586cc583f2d0

**Comment by edjroot** [comment]
Awesome, thanks again!
