### ISSUE TITLE
Different profiles for the extension

### ISSUE THREAD

**Issue by Enchufadoo** [Enchufadoo/fixedzoom#18]
Yes. I use Firefox profiles / sync for different computers, so that my bookmarks, addons, etc are saved. I use the same Firefox profile on two different computers, one with a 2160p UHD monitor and the other with a 1080p monitor. The settings from fixedzoom are synced, and since I use a lot of the same sites, with cutom zoom levels, they are off when I change computers. 

On the [ArchWiki](https://wiki.archlinux.org/) I use 110% on UHD monitor and 100% on 1080p. I can't think of another extension that does this in particular, and especially not for zoom settings. In a perfect world, there would be a button on the advanced settings that allowed you to manage "profiles". For example, mine might be "UHD" and "HD", which would toggle between which set of rules I wanted to use at that time. Then when I switched computers, I would only have to make one change instead of manually zooming in/out a lot.

_Originally posted by @saildata in https://github.com/Enchufadoo/fixedzoom/issues/15#issuecomment-447530872_

**Comment by Enchufadoo** [comment]
Added on the last version 2.1.0, first you need to enable profiles on the "Advanced settings" sector.

![imagen](https://user-images.githubusercontent.com/1263356/50577241-2205b180-0e03-11e9-889b-9294b628bc97.png)

And then create/select a new profile which will have a different zoom/rules than the default profile.

![imagen](https://user-images.githubusercontent.com/1263356/50577278-c7b92080-0e03-11e9-8f56-534e09e0d3e4.png)

**Comment by kostya-666** [comment]
Nice extension, thanks you ) Would you add possibility to connect profile to screen resolution and switch automatically on resolution change?

**Comment by kn666** [comment]
Please add functionality to change profile when screen resolution changes. Thanks)

**Comment by Enchufadoo** [comment]
Hi @kostya-666 is not possible, browser extensions can't know the resolution of the users screen.
