### ISSUE TITLE
how to create a profile for local HTML files

### ISSUE THREAD

**Issue by shawn8888** [Enchufadoo/fixedzoom#19]
I want to set a fixed zoom ratio for all local HTML files. They show on the URL bar like this:
file:///C:/Temp/aaa/abc123.download.htm
file:///C:/Temp/aaa/def346.download.htm
...
Is it possible to create a profile for that?
Thanks a lot!

**Comment by Enchufadoo** [comment]
Enable regular expressions in advanced options, select that profile, go to manage rules and create a rule like this one 

`file:\/\/\/(.*)\.htm`

The rule should look like this:

![imagen](https://user-images.githubusercontent.com/1263356/52711015-89209500-2f6f-11e9-98bc-1968b049e922.png)

Each profile has it's own rules so be sure to select the profile before creating the rule.

**Comment by shawn8888** [comment]
It works!!!
Thank you so much!

**Comment by Enchufadoo** [comment]
Glad it worked.
