### ISSUE TITLE
Impossible to install addon on Firefox ESR 64bit on Linux

### ISSUE THREAD

**Issue by nestukh** [Enchufadoo/fixedzoom#21]
First, your addon is **much faster** than zoom page we: I managed to install the 2.1.0 version from the Version History page, it worked for 2 days and was just perfect.
Then firefox has disabled it by itself, showing a message like "_Fixed Zoom cannot be verified for use in Firefox and has been disabled_" (it's so on `about:addons` as well). Impossible to update: "_there was an error downloading FIrefox Zoom_    *try again*   ".

As you can image, at first I tried to install the current version normally, but addons.mozilla.org reported "_Download failed. Please check your connection_" every time, just like described on https://github.com/mozilla/addons/issues/851

Further info:
- I have such a problem only with this addon
- on Firefox on Android 7, on the same LAN, same public IP and same internet connection, there are no problems
- when was enabled, it was able to zoom even the `about:addons` page!! (weird, also I believe not-on-specs behaviour...)
- I'm using standard Firefox ESR 60.5.1 64 bit on debian stable (stretch), https://packages.debian.org/stretch/firefox-esr for extra details

**Comment by Enchufadoo** [comment]
Hi @nestukh, you are right, I just tried it on firefox ESR on Kubuntu and I get the same error. Not on regular firefox though. 

I don't know what I could be doing so different from every other extension that it doesn't allow the installation. It's even marked as legacy on the addons page.

I'll ask on mozilla forums because I'm clueless.

> when was enabled, it was able to zoom even the about:addons page!! (weird, also I believe not-on-specs behaviour...)

It's meant to be that way, the zoom applies to every page, even firefox internal ones.

**Comment by Enchufadoo** [comment]
I found the error I think

> 1552065011711	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing commands.more-fixedzoom.suggested_key.default: Value "Ctrl+Alt+Period" must either: match the pattern /^\s*(Alt|Ctrl|Command|MacCtrl)\s*\+\s*(Shift\s*\+\s*)?([A-Z0-9]|Comma|Period|Home|End|PageUp|PageDown|Space|Insert|Delete|Up|Down|Left|Right)\s*$/, match the pattern /^\s*((Alt|Ctrl|Command|MacCtrl)\s*\+\s*)?(Shift\s*\+\s*)?(F[1-9]|F1[0-2])\s*$/, or match the pattern /^(MediaNextTrack|MediaPlayPause|MediaPrevTrack|MediaStop)$/ 

Apperently there's a problem with the zoom shortcuts I chose, I'll look into it.

**Comment by Enchufadoo** [comment]
Fixed on the last version (2.1.4)

**Comment by nestukh** [comment]
everything is working!! Thank you!! I'm closing the issue
