### ISSUE TITLE
All browser windows mis-titled

### ISSUE THREAD

**Issue by 3chel0n** [Enchufadoo/fixedzoom#22]
This extension makes the title of all browser windows, regardless of page or tab title, "`crossblade.her.jp@current_ger8hxpq#...`"  This annoyance rises well above the threshold of unusability.  I like the idea/purpose of the extension, and I almost donated some money for it.  Fortunately, I was finally able to determine that it was this extension causing said problem before throwing any money at it.

**Comment by Enchufadoo** [comment]
I really don´t understand what you are talking about, I can testify that the extension doesn't cause that problem. 
To be clear, it's literally impossible that the extension changes the page title in any way.

**Comment by Enchufadoo** [comment]
If you search "crossblade.her.jp" on google it will throw[ this result ](https://www.google.com/search?source=hp&ei=PDOlXM3zDpXM5OUPzpuD4AY&q=%22crossblade.her.jp%22&btnK=Google+Search&oq=%22crossblade.her.jp%22&gs_l=psy-ab.3...963.2666..2836...1.0..0.108.466.2j3......0....1j2..gws-wiz.....6..0j35i39.Vyuk-x48NIo)pointing to another extension called "zoom image"

**Comment by 3chel0n** [comment]
I owe you an apology as it seems you are partially correct.  I made the assumption that it was your extension causing the problem because I disabled each of my installed extensions one-by-one and the problem went away when I disabled yours.  **However**, on deeper investigation, it now seems that another extension is somehow interfering with yours, making yours appear to be the culprit when, in fact, it's not actually the root cause of the problem.

To be clear, it is the title in the **application window title bar**, not page titles, being changed.  Also, I've never had Zoom Image installed.

`echelon@Apophis-LT:~/.mozilla$ grep -irl "crossblade.her.jp" ./`
`./firefox/7owt59sw.default/crashes/store.json.mozlz4`
`./firefox/7owt59sw.default/datareporting/aborted-session-ping`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554177146821.25d9ae00-f6ae-48ee-a3fe-ded833ec37f6.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554330917426.ee5eb951-448d-47b9-ba3e-fa4599f86b4f.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554177691513.75e3f1e1-8d66-41fd-a847-fea57dc43581.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554313248739.5f032ce9-d088-47ce-9de4-c3fbb64d80a9.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554096566822.d4fed402-3bfc-4022-a5cb-0b6a9ab31169.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554326509148.6cea3758-a385-46c4-87b3-44d373bdcbcb.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554328307197.1adb6f8a-dab1-4e2f-830e-beaa41a833e5.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554267742475.1557249c-2fc5-4491-ac80-c25e2772626a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-04/1554218877083.c03c603c-63aa-4b09-abc9-637426965f24.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552626251232.556c1883-b7fa-4710-8fcd-312393bd325a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551632985106.09ae7eb7-010c-428a-ba92-e7e51669a7a1.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552847882443.9a48f1d7-35d2-45ef-b383-bf554f473895.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553490031378.e02d6b87-2e29-4775-bb91-1e0cda42f7fa.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551750823776.0f936794-dc3b-4dfe-8eff-c157d1065e23.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552143007350.b54835ae-2529-4b9d-ac26-ea4b96aebe88.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553378386656.8a19f32f-2d16-4eca-b8ea-52337e3a2d4f.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553961453285.3e7a533e-25a1-4a23-886e-2d2982c705a1.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552974638688.41dbebb4-a0bb-4006-bef5-1805f51a070f.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553380120217.80085962-e51e-4427-99dd-0fef75f8fbf7.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553196973545.7b3c163c-8bad-4f43-9d05-4894f438ae25.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553463497514.9b3247c4-64e7-418a-a3d1-158ab5941bbe.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553785411705.9879c9ca-999d-43b8-8dfb-ff24b23ad6e8.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552054770165.cad96cc4-33d7-4712-a97a-854b39327f09.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553704661893.49679c01-6b0a-4336-a303-ec9b171edf16.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552888099412.0b0f77c5-c6fd-48b7-adde-ab82bf46825b.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553058070384.8bee1720-23f8-4dda-974d-c3c7b2765725.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553357159925.48d4310a-3c1e-4179-b166-8142c0863c43.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552971600019.6114fc15-033d-4ae9-8ff4-b3f458599386.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553700893373.26376e4a-f363-4619-9da5-1dfcfdf3b824.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553576483904.1c0c306e-dd0a-4329-83c4-554bab751c0a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553310239918.7421080d-8c24-41b9-9903-a6ff2b02842d.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553488231304.4565c900-d8dc-49e9-96dd-f0b8c3e34d2b.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553526435819.10cdc37f-6248-4829-9969-15f3a6982554.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552885383581.eb4d5a4d-53fd-4092-bd2b-60be10fbf7dd.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553403814142.7ad382e6-97f0-4446-b3a1-a94a7b7fb6b1.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552280249758.3ebc477c-2c8d-4297-be6b-d8cef1ef8f20.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553835763703.d74493ca-9410-449f-b801-0103ff63969b.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553356482206.fcd60c03-23d2-4390-8ddb-c6801531613a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552279901125.ce213954-ac32-492b-92b5-3c5c2b098268.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551539144217.e51cc3ee-7b7d-4b6d-bad5-402ef5a5a8c5.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551991515505.c0c3e229-6755-4b93-a086-7dc93d9a5c5f.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551420286909.ad517cdc-a872-4232-a484-5c12830ce12a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552885735823.69130488-6d95-4be3-ade6-875b15fe1d38.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553895487589.ff297b61-2376-4c37-b05c-b06bada43ff0.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553925278248.f7a204fa-353f-4984-afc9-12b05a4c54ad.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552888703090.f957cc22-7a5d-4597-8499-9ed67ee6543c.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551805406672.5f390e05-6d7d-4e2b-805a-e4a25de568fd.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553356041795.9318f4d2-bbb5-4209-8c89-cf415e250355.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553456302428.ccf278d2-a0dc-4626-8b3c-0c5a51c3249b.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552712567031.374bdc54-4017-46f7-9c53-595dc3d83703.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552193527971.ab290e6d-71fe-4173-944c-389ca60ad532.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553356041787.e2b3dfd1-9af4-4f2b-bd06-7545632b17ec.event.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552543787489.bd51e0d8-1553-4500-9193-e961d42840a0.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553230972039.6e5791e8-06cd-474d-8820-c8c3ea1ca1df.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1554047340148.eea08356-d5ea-4b8a-812c-a5dff9e9b06a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552453998282.bd29f38f-0361-4425-adc8-adbb03d0dd7f.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552064398999.dfb16d05-cd3d-4466-95f3-178324376dbb.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551750764229.a419673e-479c-46be-a927-c464da702a93.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552974239200.cbf497de-d23a-4cd0-aa17-39fc4a404300.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553144552662.c5c2ac3a-e7e1-45d1-a5d0-49506493ba73.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552934942700.f953f53f-b5af-40ba-a97a-b4e9866a6103.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552849835724.c533741b-73f8-45f8-a3d2-8ed1f3634c1a.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552401631175.e7370ae5-c195-483d-b885-34df882f5542.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553801501248.7900af47-1297-4c10-9391-8afaaa06d9c1.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1553701598875.a9409aab-986b-4bb3-9a38-d48e1dc3560c.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551709579613.61e8d697-7adf-48a4-92be-5036bb39ff24.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1552886400814.272e3e94-3c09-42bf-b077-47b330086ee4.main.jsonlz4`
`./firefox/7owt59sw.default/datareporting/archived/2019-03/1551895561402.3a99ed0d-5a95-4a25-91a1-70fb1ae14c40.main.jsonlz4`
`./firefox/7owt59sw.default/prefs.js`
`./firefox/7owt59sw.default/chrome_debugger_profile/prefs.js`
`./firefox/7owt59sw.default/extensions.json`
`./firefox/7owt59sw.default/saved-telemetry-pings/41203330-b4c0-4c2c-bc7b-0b6304df0c3a`
`./firefox/7owt59sw.default/saved-telemetry-pings/415bb0f5-066a-4a67-9d5b-a45c16511f2d`
`./firefox/7owt59sw.default/saved-telemetry-pings/f00d9c3d-87fa-46ed-aff0-793d9d44bfde`
`./firefox/7owt59sw.default/saved-telemetry-pings/62650406-6794-46ab-8467-180c9abb2758`
`./firefox/7owt59sw.default/saved-telemetry-pings/cee6f4ff-4215-4b35-adfa-878168ed8982`

Of obvious interest here are `prefs.js`, `chrome_debugger_profile/prefs.js` and `extensions.json`, each of which (and others) point to another extension that is actually the culprit: [Tab Group Window](https://addons.mozilla.org/en-US/firefox/addon/tab-group-window/?src=search).  Disabling Tab Group Window does not make the problem go away.  There are only two actions that make the problem go away: (1) disabling your extension, and (2) removing Tab Group Window (I opted for the latter).  Very strange.  In any case, and again, I apologize for assuming it was your extension causing the problem as it did appear to be so.

**Comment by Enchufadoo** [comment]
No harm done, I've done the "disable extensions one by one to find an error", Firefox doesn't have clear way to debug this things.
