### ISSUE TITLE
Shouldn't reset zoom on sites with custom zoom

### ISSUE THREAD

**Issue by SpineEyE** [Enchufadoo/fixedzoom#3]
When a user clicks "Restore zoom to 100%", this should only apply for tabs that have no custom zoom set. 

I'd advise to match each tab's domain in `const restoreDefaultZoom` to a previously created temporary variable that contains all domains with custom zoom. Unfortunately, `browser.tabs.query` doesn't allow negated patterns.

**Comment by Enchufadoo** [comment]
Maybe I can track the tabs by tab id and then change the zoom back only on those on a list.
