### ISSUE TITLE
Set custom zoom to all internal config tabs

### ISSUE THREAD

**Issue by rypz79** [Enchufadoo/fixedzoom#7]
Hi,

I have set the default zoom to 120% and `layout.css.devPixelsPerPx` to 1.12 to increase Firefox UI layout size in my 13.3" 1368x768 Ubuntu OS.
 
While most "internet" (with a domain) tabs are zoomed well I have a problem with the configuration tabs i.e `about:* , moz-extension://* ` they are over-zoomed in 120% (they shouldn't be zoomed at all).

![firefox-zoom](https://user-images.githubusercontent.com/28814757/45319002-3fa6c680-b547-11e8-9e5c-5cd030ee224e.gif)

Is there an option to set the default zoom to these tabs as well ? 

TNX

**Comment by Enchufadoo** [comment]
Hi, yes I purposely did the url check against internet domains and not over "special" pages, main reason being that I wanted the check to be fast since every time you load anything I have to verify the domain, so adding another check for sites with no domain seemed as an edge case.

I will add it this week, I have to figure out how to do it... fast.

**Comment by Enchufadoo** [comment]
I added kind of what you wanted: (version 1.7.2)

if you go to "manage rules" and you start the url with a # it will match the entire string with the url.

Say you type: #moz-extension:// it will match all the adresses that have that, or about: will match about:config and about:debugging for example.

The only problem is that if there is a website like google.com/about: then it will match that address too.

**Comment by SpineEyE** [comment]
You could use regular expressions, that's what they are for... Maybe offer a checkbox to toggle between domain matching and regex the whole URL.
So in this case, with regex it would be ^moz-extension:\\/\\/

**Comment by Enchufadoo** [comment]
Yeah I thought about that too, maybe I will add it if I can think how not to over-complicate the UI.

**Comment by rypz79** [comment]
> Say you type: #moz-extension:// it will match all the adresses that have that, or about: will match about:config and about:debugging for example.

@Enchufadoo  GJ (Great Job) !! :+1: 
If you can also add an edit option to the rules that will be great.
Right now I'm rewriting/overwriting them until I reach the correct percentage for me.

TNX ALOT
:smiley:

**Comment by rypz79** [comment]
@SpineEyE said 
> You could use regular expressions, that's what they are for... Maybe offer a checkbox to toggle between domain matching and regex the whole URL.
> So in this case, with regex it would be ^moz-extension:\/\/

@Enchufadoo I think it can't be helped otherwise. 
Every sub menu like `about:preferences#general, about:preferences#home , about:preferences#preferences` etc... comes with it's own page and zoom layout.
Configuring each and every one of those `about:*#^` is exhausting.

TNX

**Comment by Enchufadoo** [comment]
@rypz79 OMG you are running a massive zoom project there hahah

I will add the regular expressions as soon as I can

(and the editing zoom rules)

**Comment by Enchufadoo** [comment]
Added the regular expression matching

First go into "advanced settings" 

![image](https://user-images.githubusercontent.com/1263356/45923632-bb96fc00-bec1-11e8-80a5-985270f0a72b.png)

Enable regular expressions

![image](https://user-images.githubusercontent.com/1263356/45923637-cfdaf900-bec1-11e8-8e76-10f8758414fb.png)

And you will be able to add them in management

![image](https://user-images.githubusercontent.com/1263356/45923641-fdc03d80-bec1-11e8-86e8-b7dc6be0e93c.png)

Also added a little button to edit rules, it's not perfect but ill improve it later
