### ISSUE TITLE
Don't change zoom for all tabs when the browser starts

### ISSUE THREAD

**Issue by SpineEyE** [Enchufadoo/fixedzoom#9]
When the browser starts with a saved session, the addon changes the zoom of all open tabs to the configured zoom, even though the addon is disabled. I recommend to delete the first call to `changeZoomInAllTabs()` in `enableSettings()`. Why is this even there?

**Comment by Enchufadoo** [comment]
If I seem to recall correctly after the changes in your pull request the extension wasn't changing the zoom after reopening the browser, so I added that. I don't use the extension in disabled mode so that got passed me, I'll see how to fix it.
